# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_feed_pb2 as data__feed__pb2


class DataFeedStub(object):
    """Message Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_sample = channel.unary_unary(
                '/datafeed.DataFeed/get_sample',
                request_serializer=data__feed__pb2.Config.SerializeToString,
                response_deserializer=data__feed__pb2.Sample.FromString,
                )


class DataFeedServicer(object):
    """Message Definition
    """

    def get_sample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataFeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_sample': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sample,
                    request_deserializer=data__feed__pb2.Config.FromString,
                    response_serializer=data__feed__pb2.Sample.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datafeed.DataFeed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataFeed(object):
    """Message Definition
    """

    @staticmethod
    def get_sample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datafeed.DataFeed/get_sample',
            data__feed__pb2.Config.SerializeToString,
            data__feed__pb2.Sample.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
