# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_feed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_feed.proto\x12\x08\x64\x61tafeed\"\x1a\n\x06\x43onfig\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"W\n\x06Sample\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07st_time\x18\x04 \x03(\x02\x12\x0e\n\x06t_diff\x18\x05 \x03(\x02\x32>\n\x08\x44\x61taFeed\x12\x32\n\nget_sample\x12\x10.datafeed.Config\x1a\x10.datafeed.Config\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_feed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=29
  _CONFIG._serialized_end=55
  _SAMPLE._serialized_start=57
  _SAMPLE._serialized_end=144
  _DATAFEED._serialized_start=146
  _DATAFEED._serialized_end=208
# @@protoc_insertion_point(module_scope)
